accounts/urls.py
from django.urls import path
from . import views
from .views import CustomPasswordChangeView, create_profiles_for_existing_users

app_name = "accounts"

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),
    path('profile/change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('create-profiles/', create_profiles_for_existing_users , name='create_profiles'),
]   

blog/urls.py
from django.urls import path
from blog.views import *


app_name = 'blog'

urlpatterns = [
    path('',blog_view, name="index_blog" ),
    path('<int:pk>' ,blog_single, name="single_blog" ),
    path('category/<str:cat_name>', blog_view, name="category"),
    path('author/<str:author_username>', blog_view, name="author"),
    path('tag/<str:tag_name>', blog_view, name="tag"),
    path('search/', blog_search, name="search"),
    path('new/', create_post, name="create_post"),
    path('post/<int:pk>/map/', post_map, name='post_map'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("" ,include("website.urls")),
    path("blog/" ,include("blog.urls")),
    path('captcha/', include('captcha.urls')),
    path("accounts/", include("accounts.urls")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *
from blog.views import *

app_name = 'website'

urlpatterns = [
    path('about',about, name="about"),
    path('',home, name="home" ),
    path('contact',contact, name="contact" ),
    path("test", test, name = "test"),
    path("newsletter",newsletter, name="newsletter"),
    path('<int:pk>' ,blog_single, name="single_blog" ),
    path("tourone", tourone, name="tourone"),
    path("tourtwo", tourtwo, name="tourtwo"),
    path("tourthree", tourthree, name="tourthree"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
  <head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}" />
    <!-- Author Meta -->
    <meta name="author" content="colorlib" />
    <!-- Meta Description -->
    <meta name="description" content="" />
    <!-- Meta Keyword -->
    <meta name="keywords" content="" />
    <!-- meta character set -->
    <meta charset="UTF-8" />
    <!-- Site Title -->
    <title>Travel</title>

    <link href='https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700' rel="stylesheet" />

    <!-- 
        CSS
        =============================================  -->
    
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">   
  </head>
  <body>
    <header id="header">
      <div class="header-top">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6 col-sm-6 col-6 header-top-left">
              <ul>
                {% if request.user.is_authenticated %}
                <li strong><a href="{% url "accounts:profile" %}">{{request.user.username}} Profile</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url "accounts:signup" %}">signup</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
          <div id="logo">
            <a href="{% url "website:home" %}"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
          </div>
          <nav id="nav-menu-container">
            <ul class="nav-menu">
              <li>
                <a href="{% url "website:home" %}">Home</a>
              </li>
              <li>
                <a href="{% url "website:about" %}">About</a>
              </li>
              <li>
                <a href="{% url "blog:index_blog" %}">Blog </a>
              </li>
              <li>
                <a href="{% url "website:contact" %}">Contact</a>
              </li>
            </ul>
          </nav>
          <!-- #nav-menu-container -->
        </div>
      </div>
    </header>
    <!-- #header -->

    {% block content %}

    {% endblock %}
    <footer class="footer-area section-gap">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>About Agency</h6>
              <p>The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Navigation Links</h6>
              <div class="row">
                <div class="col">
                  <ul>
                    <li>
                      <a href="#">Home</a>
                    </li>
                    <li>
                      <a href="#">Feature</a>
                    </li>
                    <li>
                      <a href="#">Services</a>
                    </li>
                    <li>
                      <a href="#">Portfolio</a>
                    </li>
                  </ul>
                </div>
                <div class="col">
                  <ul>
                    <li>
                      <a href="#">Team</a>
                    </li>
                    <li>
                      <a href="#">Pricing</a>
                    </li>
                    <li>
                      <a href="#">Blog</a>
                    </li>
                    <li>
                      <a href="#">Contact</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget">
              <h6>Newsletter</h6>
              <p>For business professionals caught between high OEM price and mediocre print and graphic output.</p>
              <div>
                <form 
                action="{% url "website:newsletter" %}" method="post" class="subscription relative">
                  {% csrf_token %}
                  <div class="input-group d-flex flex-row">
                    <input name="email" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email" />
                    <button class="btn bb-btn" type="submit"><i class="lnr lnr-location"></i></button>
                  </div>
                  <div class="mt-10 info"></div>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="single-footer-widget mail-chimp">
              <h6 class="mb-20">InstaFeed</h6>
              <ul class="instafeed d-flex flex-wrap">
                <li>
                  <img src="{% static 'img/i1.jpg' %}" alt="" />
                </li>
                <li>
                  <img src="{% static 'img/i2.jpg' %}" alt="" />
                </li>
                <li>
                  <img src="{% static 'img/i3.jpg' %}" alt="" />
                </li>
                <li>
                  <img src="{% static 'img/i4.jpg' %}" alt="" />
                </li>
                <li>
                  <img src="{% static 'img/i5.jpg' %}" alt="" />
                </li>
                <li>
                  <img src="{% static 'img/i6.jpg' %}" alt="" />
                </li>
                <li>
                  <img src="{% static 'img/i7.jpg' %}" alt="" />
                </li>
                <li>
                  <img src="{% static 'img/i8.jpg' %}" alt="" />
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- End footer Area -->

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    {% comment %} <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script> {% endcomment %}
    {% comment %} <script src='https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA'></script> {% endcomment %}
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/easing.min.js' %}"></script>
    <script src="{% static 'js/hoverIntent.js' %}"></script>
    <script src="{% static 'js/superfish.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test</title>
</head>
<body>
    <form action="{% url "website:test" %}" method="post">
        {% csrf_token %}
        <label>name:</label>
        <input type="text" name="name"><br>
        <label>email:</label>
        <input type="email" name="email"><br>
        <label>subject:</label>
        <input type="text" name="subject"><br>
        <label>message:</label>
        <input type="text" name="message"><br>
        <button type="submit">submit</button>
    </form>
</body>
</html>